setup.py
Because this exists: https://github.com/markqvist/Reticulum/blob/master/RNS/vendor/configobj.py#L22
=> Record dependency on six

RNS/Interfaces/TCPInterface.py
Had the following error when trying to run Reticulum on OSX High Sierra:
```
line 115, in set_timeouts_osx
sock.setsockopt(socket.SOL_SOCKET, socket.SO_KEEPALIVE, 1)
NameError: name 'sock' is not defined
```
This fix solved the problem for me.
(Also git added the newline at the end of the file, not sure if no-newline at EOF is intentional or not)
=> OSX NameError fix

docs/source/using.rst
Fix documentation: rncp called instead of rnx in rnx example
=> Fix a typo

docs/source/gettingstartedfast.rst, docs/source/understanding.rst
Just some typo fixes and I also removed obsolete information about `rnsconfig`.
PS. I didn't commit the build html files since I'm getting a lot of diffs compared to upstream (I guess due to different sphinx versions).
=> docs: Fix typos, remove old info about rnsconfig

RNS/Transport.py
Let me preface this by saying that I have no idea if this patch is correct or not and if this is really a bug or I'm doing something wrong ^_^.
I'm trying out the Announce example and I noticed that when I set `aspect_filter` to `None`, the callback would error out with:
```
[2023-01-26 19:50:58] [Error] Error while processing external announce callback.           
[2023-01-26 19:50:58] [Error] The contained exception was: local variable 'announce_identity' referenced before assignment
```
Looking at the codebase, it makes sense since we never assigned the `announce_identity` variable. We're only assigning it if `aspect_filter` is not `None`, but I think we should be assigning it regardless of `aspect_filter`'s value.
if this isn't a bug, is there something else I'm missing?
=> Fix bug where announce_identity could be undefined

Examples/Channel.py, RNS/Channel.py, RNS/Link.py, RNS/Packet.py, RNS/__init__.py, docs/source/examples.rst, docs/source/reference.rst, tests/all.py, tests/channel.py, tests/link.py
`Channel` provides a reliable delivery layer over `Packet`. Where `Packet` has proof of delivery, `Channel` adds automatic retries.
Additionally, `Channel` provides a mechanism for exchanging a variety of developer-defined structured data over a link. Messages are processed by a chain of handlers on the opposite end.
The result is a continuous, bidirectional object stream over  a `Link`. In pursuit of #205.
* Coordinated with maintainer
* Unit and integration automated tests added
* Test suite run and passed
* Example added and tested
* Documentation added to code and pages; built and verified; only source committed
=> Channel: reliable delivery over Link

RNS/Cryptography/HKDF.py
I started looking into the IFAC parts a bit more closely which led me to this.
The second if isn't needed since we initialize the salt with zeroes earlier. If instead we meant to pass an empty bytes class to the HMAC implementation, the end result would be the same, since it's gonna get padded with zeroes in the HMAC code.
=> hkdf: Remove duplicate check if the salt is None

RNS/Interfaces/AutoInterface.py
The code previously dropped scope identifiers expressed as a trailing "%ifname", which happens on macOS.  On NetBSD and OpenBSD (and likely FreeBSD, not tested), the scope identifier is embedded.  Drop that form of identifier as well, because we keep address and ifname separate, and because the scope identifier must not be part of computing the hash of the address.
Resolves #240, failure to peer on NetBSD and OpenBSD.
=> AutoInterface: Drop embedded scope identifier on fe80::

Examples/Buffer.py, RNS/Buffer.py, RNS/Channel.py, RNS/__init__.py, docs/source/examples.rst, docs/source/reference.rst, tests/channel.py, tests/link.py
`Buffer` uses `Channel` to provide a stream-like interface that operates over `Link`. `Buffer` is not a distinct type but rather provides functions to wrap `RawChannelReader` and `RawChannelWriter` in Python's buffered stream providers.
The result is uni- or bi-directional stream objects that are not limited by packet sizes (like `Channel` messages are).
- Coordinated with maintainer
- Unit and integration automated tests added
- Test suite run and passed
- Example added and tested
- Documentation added to code and pages; built and verified; only source committed
=> Buffer: send and receive binary data over Channel

RNS/Buffer.py, RNS/Channel.py, RNS/Interfaces/LocalInterface.py, RNS/Link.py, RNS/Transport.py, tests/channel.py, tests/link.py
@markqvist This hopefully resolves the issues you were experiencing. I was able to reproduce similar issues and I think they are retry-related. As part of the fix, I added a protected variable to LocalInterface to allow tests to simulate links with constrained bandwidth. It was my first and ignorant crack at it, do feel free to push back if you don't like it.
I am not certain that the problem was just that the retry timer was too short. It could be additional complications due to half duplex or actual lost packets from the physical channel. I'll need to set up a proper LoRa test rig to really see what's going on with that.
- StreamDataMessage now packed by struct rather than umsgpack for a more predictable size
- Added protected variable on LocalInterface to allow tests to simulate a low …
=> Bugfix: buffer missing segments

RNS/Interfaces/LocalInterface.py
On Linux, SO_REUSEADDR is used so that a socket in TIME-WAIT state can be rebound after a listening process is restarted. It does not allow two processes to listen on the exact same (addr, port) combination. However, on Windows, it does, and SO_EXCLUSIVEADDRUSE is required to reproduce the Linux behavior.
Reticulum relies on an error being returned by bind() that reuses the same (addr, port) combination as another process to detect whether there is a shared instance already running. Setting SO_EXCLUSIVEADDRUSE makes this detection process work on Windows as well.
=> Use SO_EXCLUSIVEADDRUSE instead of SO_REUSEADDR on Windows

RNS/Utilities/rnodeconf.py
The changes in this PR make it possible to flash a LilyGO T3 V1.6.1 with a `rnodeconf --autoinstall` invocation.
I've only tested this PR on Windows, however the changes are written to be compatible with *nix systems.
=> Improve Windows compatibility

RNS/Interfaces/Android/RNodeInterface.py, RNS/Interfaces/RNodeInterface.py
This this will otherwise lead to the error:
AttributeError: 'RNodeInterface' object has no attribute 'r_stat_snr'
=> RNodeInterface - Fixed missing init of 'r_stat_snr'.

RNS/Utilities/rnodeconf.py
The `--eeprom-dump` mechanism tries to dump the eeprom in the current directory under `./eeprom/`, but this fails if the eeprom directory doesn't exist and it's not obvious to the user that they should create this dir.
This patch will instead dump the eeprom under a new directory in `CNF_DIR`, the same same way as all the other dump/extract commands do. Here's an example output of this:
```
(reticulum2) redteamoricono ~/Code/Python/Reticulum % rnodeconf --eeprom-backup /dev/ttyUSB0
[17:09:40] Opening serial port /dev/ttyUSB0...                                                             
[17:09:43] Device connected                                                                                
[17:09:43] Current firmware version: 1.62 …
```
=> rnodeconf: Dump eeprom under specific directory

RNS/Utilities/rnodeconf.py
As discussed on Matrix not long ago. This just adds a suggestion after rnodeconf fails to flash on ESP32 due to speed issues. T
=> Added suggestion to use lower baudrate if flashing fails on ESP32

RNS/Utilities/rnodeconf.py
Adds NRF52 support. Currently boards are provisioned as homebrew.
=> Add NRF52 support

RNS/Utilities/rnodeconf.py
Also fixed alternate version downloads which were failing with "Could not read locally cached release information."
Note that this area of code could probably use some refactoring to be more straight-forward but I didn't want to make more assumptions than necessary.
=> Support for alternate download URL for custom firmware images

RNS/Utilities/rnodeconf.py
Base support for Heltec V3 board as serial only.
=> Add product and model, plus support for Heltec V3 serial only setup to rnodeconf.

docs/source/gettingstartedfast.rst
Hi, how are you? 
Well, reading the documentation I found this typo. Also deleted some trailing spaces.
I would like to contribute with the documentation in Spanish. Where are the different languages hosted? I don't see it in this repo...
Thank you for creating Reticulum!
=> docs: Fix a typo. startig / starting

RNS/Interfaces/AutoInterface.py, RNS/Reticulum.py, docs/manual/_sources/interfaces.rst.txt, docs/source/interfaces.rst
**Description**
This implementation allows defining the type of IPv6 multicast address in the AutoInterface configuration.
**Problem**
It has been observed that the WiFi mesh device TP-Link Deco M5 (AC1300 model), doesn't allow IPv6 multicast packet traffic of temporary address types (ff12::/16).
**Tests**
The various tests conducted indicate that, when changing the IPv6 packet type to "permanent", Permanent Multicast Address, ff02::/16, the WiFi AP successfully retransmits the packet. Tests were carried out with different operating systems and some spare Wifi APs from different brands.
**Solution**
Allow defining the type of address in the configuration file between "temporary", default, ff12::/16, and "permanent", ff02::/16.
**Thoughts**
Maybe the TP-Link Deco M5 device has blocked …
=> feat: implement multicast address type definition on AutoInterface configuration

Examples/Echo.py, Examples/Link.py
Surface the transparent core option to load the server identity from file in addition to creating it dynamically.
Why in the example:
1. Show the option without changing the default behavior. To make use of it, simply create/drop-in an identity file into the "storage/identities" config sub directory.
2. Saves cut-n-paste eg. if the example is used often.
This feature is transparent and optional.
Note: I'm working on getting the Java Reticulum implementation up to scratch and not having to cut-n-paste on every launch comes in handy. I've built this into the Java equivalent of the Echo and Link Examples as well.
=> optionally load identity file from file in Echo and Link examples

RNS/Utilities/rnodeconf.py
As noted in #498 at least some drivers or versions of Windows set DTR to low when the COM port disconnects. This commit adds a delay to the disconnect to give the MCU time to write the configuration and shut down gracefully. It accomplishes this in two ways:
First, a one second delay is added to the `RNode.leave` function. This appears to be all that is actually needed.
Second, for a failover, all instances of `exit()` have been replaced with `graceful_exit()`. In addition, the fall-through at the end of `main()` explicitly calls `graceful_exit`.
This function defaults to code 0, but accepts and passes through any integer to `exit()`. It calls additional logic only on Windows systems, calling `leave` if the RNode object still exists, and closes `rnode_serial` if it's still open. Note: I …
=> Windows DTR timing fix

RNS/Interfaces/AutoInterface.py, RNS/Reticulum.py, RNS/vendor/ifaddr/niwrapper.py
This PR adds support for using the `AutoInterface` on Windows machines.
I have tested the following setups, and they appear to be working!
**Setup 1**
- MacBook Pro connected to Ethernet with `AutoInterface`
- Windows 10 PC connected to Ethernet with `AutoInterface`
- MacBook can exchange announces, messages and files with Windows 10 (tested Sideband and WebChat)
- `rnpath` to MacBook from Windows PC shows roundtrip time of ~33ms with 1 hop
- `rnpath` to EchoBot from Windows PC times out, as there is no path yet
**Setup 2**
- MacBook Pro connected to;
- Ethernet with `AutoInterface`
- RNS Testnet Amsterdam via `TCPClientInterface`
- Windows 10 PC connected to Ethernet with `AutoInterface`
- `rnpath` to EchoBot from Windows PC shows a rountrip time of ~893ms with 4 hops
- `rnprobe` to …
=> Implement AutoInterface support on Windows

RNS/Utilities/rnodeconf.py
Very, very useful feature when debugging firmware verification issues.
Command line arguments are totally negotiable, I just assigned them to whatever.
=> Add ability to get target and calculated firmware hash from device

RNS/Utilities/rnodeconf.py
As the title states, this makes it possible to flash RAK4631 boards successfully on Mac.
=> Fix for macos failing to set firmware hash on NRF52

RNS/Utilities/rnodeconf.py
typo in Reticulum/RNS/Utilities/rnodeconf.py (egraceful_xit())
that cause a crash if we run rnodeconf -i on an unprovisioned node
(for context I'm trying to make a rnode using an ESP32-C3 and a XL1278-SMT.
I figured out how to compile new firmware image using the arduino CLI and might have a few thing to write in a separate discussion regarding the procedure to create new node. there are a few small issue to wrinkle but I need to first get a hang of the whole codebase.
currently i'm stuck while trying to bootstrap the eeprom but I fail to understand how it works and what is stored on that eeprom. Still trying to find a revelant discussion about that and might create a new one if that fail.
anyway thanks for this amazing tool.
I'm having fun trying to make my little rnode :)
(next time I …
=> fixed small typo : egraceful_xit()

Examples/Link.py
Allow server side to exit by entering 'quit', executing a proper teardown() and consequently notifying the initiator via callback.
=> Link example - Allow server to gracefully exit

RNS/Utilities/rnodeconf.py
Initializes `selected_model` with the value of model specified on the command line.
=> Fix for broken `--rom` manual device provisioning

RNS/Interfaces/Android/RNodeInterface.py, RNS/Interfaces/RNodeMultiInterface.py, RNS/Reticulum.py
This PR adds interface support for RNodes with multiple interfaces on board.
Firmware version 1.73 and up (community edition) is required on the RNode to
utilise this interface type.
Please see the below example for details on how to configure this interface
type (it would be wise to add it to the RNS manual):
```
[[openCom XL]]
type = RNodeMultiInterface
interface_enabled = True
port = /dev/ttyACM0
[[[HIGHDATARATE]]]
interface_enabled = True
frequency = 2400000000
bandwidth = 1625000
txpower = 0
vport = 1
spreadingfactor =        5
codingrate = 5
[[[LOWDATARATE]]]
interface_enabled = True
frequency = 865600000
vport = 0
bandwidth = 125000
txpower = 0
spreadingfactor = 5
codingrate = 5
```
I have also included a commit to update the minimum supported spreading factor
for the Android …
=> Add RNodeMultiInterface support

RNS/Utilities/rnodeconf.py
Adds the product and model values required for rnodeconf to recognise the openCom XL.
=> Add support for openCom XL

RNS/Interfaces/RNodeMultiInterface.py
I forgot to check if CMD_INT4_DATA conflicted with any other bytes assigned to frames. It conflicts with CMD_ERROR. I've made the necessary changes to fix this issue.
The branch `frame-fix` will be merged for version `1.74` of the CE firmware. This should ideally be merged just after that point to prevent causing issues of requiring a non-existent firmware version ;)
=> Fix RNodeMultiInterface interface framing

RNS/Interfaces/RNodeMultiInterface.py, RNS/Reticulum.py
This one's on me. So, when I designed RNodeMultiInterface, it didn't occur to me that the interface values being set in `Reticulum.py` would not actually be set until after the class was initialised. And since these values are passed on to the `RNodeSubInterface` before they're actually initialised, this created a problem. The actual values will never be set in the subinterface (which is the one actually processing packets).
The way this manifested as a bug was in the fact that `self.OUT` would be set to false on all RNodeSubInterface instances until the interface was destroyed and recreated (i.e. through pulling the connection to the RNode). So, every first connection when the RNS daemon started would result in it not being able to transmit on any of the RNodeSubInterface instances. This …
=> Fix interface values not being set on RNodeSubInterface instances

RNS/Interfaces/TCPInterface.py
As per commit.
(Single line commit: BIG BRAIN :brain: )
---
Still haven't yet figured out the bind-side of things for the equivalent `TCPServerInterface` because I see the mention of class, rather than instance, variables and that seems sus to tamper with (I don't know Python, so I'd rather not)
=> Support IPv6 for outbound TCP interface (TCPClientInterface)

RNS/Interfaces/TCPInterface.py
Before we call the `socket.socket(...)` constructor function, let us first provide `self.target_ip` and `self.target_port` to `socket.getaddrinfo(...)` (static function) and then get the AF family from it. Then we pass this into the ctor
=> Determine AF FAMILY from getaddrinfo BEFORE socket ctor

RNS/Interfaces/TCPInterface.py
If an interface has an IPv6 address record associated with it then, and only then, prefer that.
Otherwise AF_INET is used (Ipv4 address)
=> Allow binding to IPv6 (if present)

RNS/Interfaces/KISSInterface.py
Two issues were resolved with KISS interface beacon transmissions:
1. Fixed frame length handling to meet minimum length requirements (15 bytes) for TNCs like Direwolf. Previously, raw beacon data was being sent directly, causing frame length errors:
```
<<< Data frame from KISS client application, channel 0, total length = 11
000:  c0 00 44 4e 39 54 54 2d 31 35 c0                 ..FOOBAR-15.
Frame length 8 not in allowable range of 15 to 2123.
ERROR - Invalid KISS data frame from client app.
```
2. Added standard 0xAA 0xAA sync pattern to improve radio modem synchronization and compatibility with packet radio protocols like FX.25 and IL2P.
This ensures:
- Proper frame length for TNC compatibility
- Better bit synchronization with standard sync pattern
- Improved reception reliability
- …
=> Fix KISS beacon frame formatting and add sync pattern

RNS/Utilities/rnodeconf.py
This PR supersceeds and extends PR #733 , it incorporates recent cleanup, uses the correct frequency range for the SX1262, and has the autoinstall section more completely defined.
It assumes the support for the XIAO/WIO board has been incorporated from the CE RNode project : [7342116](https://github.com/liberatedsystems/RNode_Firmware_CE/commit/7342116d91221391376cb7cc4e107d648c32a0d7) & [ea77f3b](https://github.com/liberatedsystems/RNode_Firmware_CE/commit/ea77f3b32e6eae68a9bfd2290d1c6efb62af071d) : and that the firmware from that is available in the releases folder + json index for autoinstall.
Apologies if this is already covered and un-needed. I have been setting up this board for myself, and needed a working rnodeconf for that; so it seemed sensible to offer it here. 
Also note that …
=> add rnodeconf support for SeeedStudio XIAO esp32s3 wio

RNS/Interfaces/RNodeMultiInterface.py
This only affects RNodeMultiInterface.
=> Fix announce cap crash when transport mode enabled

RNS/Utilities/rnstatus.py
Add check to ensure `management_identity` is provided when using remote query flag (`-R`). Prevents `TypeError` and provides clear error message when user forgets to specify identity file with `-i` flag.
Before: `expected str, bytes or os.PathLike object, not NoneType`
After: `Remote management requires an identity file. Use -i to specify the path to a management identity.`
Fixes #792
=> fix(rnstatus): Add validation for missing -i flag when using -R
